version: "3.8"

services:
  sentiment_api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - MODEL_PATH=models/sentiment_model.pt