version: "3.9"

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Streamlit sur localhost:8000
    volumes:
      - .:/app
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8001:8000"  # API sera disponible sur localhost:8001
    volumes:
      - .:/app
