name: Build Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t sentiment-api .

      - name: Test Docker container
        run: docker run -d -p 8000:8000 sentiment-api
