name: Build and Push Docker Image

on:
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
      - 'src/**'
      - 'requirements.txt'

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set IMAGE_NAME environment variable
        run: |
          REPO="${{ github.repository }}"
          # Nettoyage : minuscules + remplacement _ → - + suppression du - final s'il existe
          REPO_CLEAN=$(echo "$REPO" | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g' | sed 's/-$//')
          IMAGE_NAME="ghcr.io/$REPO_CLEAN"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "Image name: $IMAGE_NAME"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME:latest

      - name: Run Docker image (optional sanity check)
        run: docker run --rm $IMAGE_NAME:latest

      - name: Push image to GHCR
        run: docker push $IMAGE_NAME:latest
