name: Build and Push Docker Image

on:
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
      - 'src/**'
      - 'requirements.txt'

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set IMAGE_NAME environment variable
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME:latest

      - name: Run Docker image
        run: docker run $IMAGE_NAME:latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GHCR
        run: docker push $IMAGE_NAME:latest
