name: Evaluate Model

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  evaluate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run evaluation
        run: python src/evaluate.py

      - name: Upload evaluation metrics
        uses: actions/upload-artifact@v3
        with:
          name: eval-metrics
          path: metrics.json
