name: Run Tests and Lint

on: [push, pull_request]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 torch transformers datasets
          python -m spacy download fr-core-news-sm

      - name: Lint code
        run: flake8 src/ tests/

      - name: Run unit tests
        run: python -m unittest discover tests/unit
