name: Run Tests and Lint

on: [push, pull_request]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Show requirements.txt content
        run: cat requirements.txt

      - name: Install dependencies
        run: |
          rm -rf ~/.cache/pip
          pip install --no-cache-dir -r requirements.txt
          pip install flake8
          pip install https://github.com/explosion/spacy-models/releases/download/fr_core_news_sm-3.7.0/fr_core_news_sm-3.7.0-py3-none-any.whl

      - name: Lint code
        run: flake8 src/ tests/

      - name: Run unit tests
        run: python -m unittest discover tests/unit
